/// Flutter icons StockIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  StockIcons
///      fonts:
///       - asset: fonts/StockIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class StockIcons {
  StockIcons._();

  static const _kFontFam = 'StockIcons';
  static const String? _kFontPkg = null;

  static const IconData menu = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData export_icon = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData programming = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData market = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sales = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData homepage = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stock = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
